version: '3.1'

services:
  app:
    build:
      context: ./
    working_dir: /app
    ports:
        - "8080:8080"        
    volumes:
      - .:/app
    command: sh -c 'apk add --no-cache git gcc g++ make && go test --tags=unit_tests -v ./...'
networks:
  default:
    external:     
      name: network
                  