version: "3.1"
services:
    test_app:
        image: golang:1.13-alpine3.10     
        volumes:
            - .:/app
        working_dir: /app
        environment:
            - API_TEST_DOMAIN=http://app.network:8080
        command: sh -c 'apk add --no-cache git gcc g++ make && ./scripts/wait-for.sh app.network:8080 -t 300 -- go test --tags=integration_tests -v ./...'