# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      context: ./
    working_dir: /app
    ports:
        - "8080:8080"        
    volumes:
      - .:/app
    depends_on:
        - "mysql"
    environment:
        - MYSQL_ADDRESSES=mysql.network:3306
        - MYSQL_DATABASE=order
    command: sh -c './scripts/init.sh && go run main.go'
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: order_service
      MYSQL_PASSWORD: password      
    ports:
      - 3306:3306        
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8081

networks:
  default:
    external:     
      name: network
                  